### PR TITLE
Added vulture

### PR DESCRIPTION
**Pull request by ryuk201198**

### CODE REVIEW

**Comment by Loonie-Toons** [comment]
Manually merged.

**Comment by ryuk201198** [comment]
there might be a problem with string.csv VultureInfoLong

**Comment by ryuk201198** [comment]
Also check the OptionHolder.cs I added Vulture.SetupCustomOption() in between the workaholic's options 😐

**Comment by Loonie-Toons** [comment]
I rewrote VultureInfoLong and I made sure Vulture settings were in the right place ;)

**Pull request closed without merging**
