### PR TITLE
Added Copycat, Plaguebearer, a setting for vulture and a fix

### PR DESCRIPTION
**Pull request by ryuk201198**
1. Added Copycat
2. Added Plaguebearer
3. Fix Vulture eat cd animation shown after death
4. Vulture setting imp vision on/off

### CODE REVIEW

**Comment by Loonie-Toons** [comment]
Did you figure out the bugged Cultist/Infectious/Virus win conditions yet?

**Comment by ryuk201198** [comment]
no

**Comment by Loonie-Toons** [comment]
welp

**Comment by Loonie-Toons** [comment]
did you test it to see if you simply broke it on the previous version somehow?

**Comment by ryuk201198** [comment]
I will test it in sometime

**Comment by Loonie-Toons** [comment]
mmk

**Comment by vdpcool** [comment]
Hello guys

**Pull request merged**
