### PR TITLE
Lurker

### PR DESCRIPTION
**Pull request by lars-wu**
Added a new Impostor role: Lurker

InfoLong:
As a lurker, you can jump into a vent to reduce your cooldown by a certain number of seconds. After you kill, your cooldown is reset to its original value.

### CODE REVIEW

**Comment by lars-wu** [comment]
updatet it

**Comment by Loonie-Toons** [comment]
Hm, doesn't seem to be.
image

**Comment by lars-wu** [comment]
Spiritcaller is not *officially* merged yet

**Comment by Loonie-Toons** [comment]
Oh right, I just woke up a little bit ago lmao

**Comment by Loonie-Toons** [comment]
Alright there, now it is.

**Comment by lars-wu** [comment]
Ok, updated

**Pull request merged**
