### PR TITLE
Add Untranslated Simplified Chinese

### PR DESCRIPTION
**Pull request by CrewCyan**
Added some simplified Chinese without translation

### CODE REVIEW

**Comment by ninyouyigehao** [comment]
患者我补上了

**Comment by CrewCyan** [comment]
I have added the Simplified Chinese translation of Sunclasses

**Comment by CrewCyan** [comment]
> 患者我补上了

I have added the Simplified Chinese translation of Sunclasses

**Comment by ninyouyigehao** [comment]
Okay, I will speak English.

**Comment by ninyouyigehao** [comment]
I changed some translations.

**Pull request merged**
